"""Ollama implementation of the provider-independent LLM port."""

from __future__ import annotations

from typing import Any

import httpx

from researchpilot.domain.ports import LLMProviderError

OLLAMA_PROVIDER_NAME = "ollama"


class OllamaError(LLMProviderError):
    """An Ollama request failure safe to show to a user."""


class OllamaResponseError(OllamaError):
    """An Ollama response envelope that cannot be consumed."""


class OllamaProvider:
    """Generate non-streaming JSON-schema-constrained output with Ollama."""

    def __init__(
        self,
        client: httpx.Client,
        *,
        base_url: str,
        model: str,
    ) -> None:
        model = model.strip()
        if not model:
            raise ValueError("Ollama model must not be empty")
        self._client = client
        self._endpoint = f"{base_url.rstrip('/')}/api/generate"
        self._model = model

    @property
    def provider_name(self) -> str:
        return OLLAMA_PROVIDER_NAME

    @property
    def model_name(self) -> str:
        return self._model

    def generate(
        self,
        *,
        system_prompt: str,
        prompt: str,
        response_schema: dict[str, Any],
    ) -> str:
        """Return the raw structured output generated by Ollama."""

        try:
            response = self._client.post(
                self._endpoint,
                json={
                    "model": self._model,
                    "system": system_prompt,
                    "prompt": prompt,
                    "format": response_schema,
                    "stream": False,
                    "options": {"temperature": 0},
                },
            )
            response.raise_for_status()
        except httpx.TimeoutException as exc:
            raise OllamaError("Ollama request timed out") from exc
        except httpx.HTTPStatusError as exc:
            message = self._error_message(exc.response)
            raise OllamaError(
                f"Ollama returned HTTP {exc.response.status_code}: {message}"
            ) from exc
        except httpx.RequestError as exc:
            raise OllamaError(
                "Ollama is unavailable. Ensure the local server is running "
                f"and reachable at {self._endpoint}: {exc}"
            ) from exc

        try:
            payload = response.json()
        except ValueError as exc:
            raise OllamaResponseError("Ollama returned malformed JSON") from exc
        if not isinstance(payload, dict):
            raise OllamaResponseError("Ollama response must be a JSON object")
        if error := payload.get("error"):
            raise OllamaResponseError(f"Ollama generation failed: {error}")
        raw_output = payload.get("response")
        if not isinstance(raw_output, str) or not raw_output.strip():
            raise OllamaResponseError("Ollama response is missing generated text")
        if payload.get("done") is not True:
            raise OllamaResponseError("Ollama response did not finish generation")
        return raw_output

    @staticmethod
    def _error_message(response: httpx.Response) -> str:
        try:
            payload = response.json()
        except ValueError:
            return response.reason_phrase or "request failed"
        if isinstance(payload, dict) and isinstance(payload.get("error"), str):
            return payload["error"]
        return response.reason_phrase or "request failed"
